[package]
name = "ray"
version = "0.1.0"
authors = ["thomas hugon <thomas_hugon_1@carrefour.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"